# Generated by Django 5.1.1 on 2024-12-01 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='colors',
        ),
    ]
