# Generated by Django 5.1.1 on 2024-12-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_deal_delete_deals'),
    ]

    operations = [
        migrations.CreateModel(
            name='PC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('badge', models.CharField(choices=[('Best Seller', 'Best Seller'), ('New Arrival', 'New Arrival'), ('Best Value', 'Best Value')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('savings', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('review_count', models.IntegerField()),
                ('financing_info', models.CharField(max_length=255)),
                ('gpu', models.CharField(max_length=255)),
                ('cpu', models.CharField(max_length=255)),
                ('ram', models.CharField(max_length=255)),
                ('storage', models.CharField(max_length=255)),
                ('cooling', models.CharField(max_length=255)),
                ('fps_1440p', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fps_4k', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ray_tracing', models.BooleanField(default=False)),
                ('psu', models.CharField(max_length=255)),
                ('image_main', models.ImageField(upload_to='product_images/')),
                ('image_gallery', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('case_lighting', models.CharField(choices=[('RGB (MSI Mystic Light)', 'RGB (MSI Mystic Light)'), ('White LED', 'White LED'), ('No Lighting', 'No Lighting')], max_length=50)),
                ('ram_configuration', models.CharField(choices=[('32GB DDR5-6000 (2x16GB)', '32GB DDR5-6000 (2x16GB)'), ('64GB DDR5-6000 (4x16GB) (+$299)', '64GB DDR5-6000 (4x16GB) (+$299)'), ('128GB DDR5-6000 (4x32GB) (+$599)', '128GB DDR5-6000 (4x32GB) (+$599)')], max_length=50)),
                ('warranty', models.CharField(choices=[('2 Year Standard Warranty', '2 Year Standard Warranty'), ('3 Year Extended Warranty (+$199)', '3 Year Extended Warranty (+$199)'), ('4 Year Premium Warranty (+$299)', '4 Year Premium Warranty (+$299)')], max_length=50)),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
    ]
