# Generated by Django 5.1.1 on 2024-12-01 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_pc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pc',
            name='financing_info',
        ),
    ]
