# Generated by Django 5.1.1 on 2024-12-01 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_pc_financing_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pc',
            name='image_main',
        ),
    ]
