# Generated by Django 5.1.1 on 2024-12-01 12:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_pc_image_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='pc',
            name='image_main',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='product_images/'),
            preserve_default=False,
        ),
    ]
