# Generated by Django 5.1.1 on 2024-12-01 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_pc_image_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pc',
            name='image_gallery',
        ),
    ]
