# Generated by Django 5.1.1 on 2024-12-01 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_accessory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessory',
            name='image_url',
        ),
    ]
