# Generated by Django 5.1.1 on 2024-12-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_accessory_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
